# This the default nodeport.yaml manifest for nginx-ingress.  
# The port name MUST be changed to work the new NLK Controller.
# See the new loadbalancer-nlk.yaml or nodeport-nlk.yaml file example.
# 
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
