{
 "title": "NGINX K8s LB",
 "description": "NGINX Plus Prometheus Exporter",
 "tags": [ "nginx" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(up, instance)" } },
   { "name": "upstream", "query": { "query": "label_values(upstream)" } }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_http_requests_total[1h]))"
    }
   ]
  },
  {
   "title": "Total (2XX from upstream) requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"2xx\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total (4XX from upstream) requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"4xx\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total (5XX from upstream) requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"5xx\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginxplus_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum (irate(nginxplus_http_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "LB Server Resp Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(nginxplus_upstream_server_response_time{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "LB Upstream Requests",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginxplus_upstream_server_requests{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{ upstream }} - {{ server }}"
    }
   ]
  },
  {
   "title": "LB Upstream Resp Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(nginxplus_upstream_server_response_time{instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Processed connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginxplus_connections_accepted{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "sum(irate(nginxplus_connections_accepted[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginxplus_connections_active{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(nginxplus_connections_active)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "2XX status code (rate over 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"2xx\"}[5m]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "4XX status code (rate over 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"4xx\"}[5m]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "5XX status code (rate over 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"5xx\"}[5m]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  }
 ]
}