apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nlk.apikeyname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  nginxaasApiKey: {{ .Values.nlk.dataplaneApiKey | toString | b64enc }}
