apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nlk.configName" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
{{- with .Values.nlk.config.logLevel }}
    log-level: "{{ . }}"
{{- end }}
{{- with .Values.nlk.config.nginxHosts }}
    nginx-hosts: "{{ . }}"
{{- end }}
    tls-mode: "{{ .Values.nlk.config.tls.mode }}"
{{- with .Values.nlk.config.serviceAnnotationMatch }}
    service-annotation-match: "{{ . }}"
{{- end }}
