apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nlk.fullname" . }}
  namespace: nlk
  annotations:
    kubernetes.io/service-account.name: {{ include "nlk.fullname" . }}
type: kubernetes.io/service-account-token
