apiVersion: v1
kind: ConfigMap
metadata:
  name: nlk-config
  namespace: nlk
data:
{{- if .Values.nlk.config.entries.hosts }}
  nginx-hosts: "{{ .Values.nlk.config.entries.hosts }}"
{{- end }}
  tls-mode: "{{ index .Values.nlk.defaultTLS "tls-mode" }}"
  ca-certificate: "{{ index .Values.nlk.defaultTLS "ca-certificate" }}"
  client-certificate: "{{ index .Values.nlk.defaultTLS "client-certificate" }}"
  log-level: "{{ .Values.nlk.logLevel }}"

