apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "nginx-loadbalancer-kubernetes:resource-get-watch-list"
  namespace: nlk
subjects:
  - kind: ServiceAccount
    name: nginx-loadbalancer-kubernetes
    namespace: nlk
roleRef:
  kind: ClusterRole
  name: resource-get-watch-list
  apiGroup: rbac.authorization.k8s.io
