nlk:
  name: nginxaas-operator

  kind: deployment

  replicaCount: 1

  image:
    registry: registry-1.docker.io
    repository: nginx/nginxaas-operator
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: release-0.1.0

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Automatically mount a ServiceAccount's API credentials?
    automount: true
    # Annotations to add to the service account
    annotations: {}

  config:
    entries:
      hosts:
        ""

  defaultTLS:
    tls-mode: "no-tls"
    ca-certificate: ""
    client-certificate: ""

  dataplaneApiKey: ""

  logLevel: "warn"

  containerPort:
    http: 51031

  liveStatus:
    enable: true
    port: 51031
    initialDelaySeconds: 5
    periodSeconds: 2

  readyStatus:
    enable: true
    port: 51031
    initialDelaySeconds: 5
    periodSeconds: 2

rbac:
  ## Configures RBAC.
  create: true
