nlk:
  name: nginxaas-operator

  kind: deployment

  replicaCount: 1

  image:
    registry: registry-1.docker.io
    repository: nginx/nginxaas-operator
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: release-0.1.0

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Automatically mount a ServiceAccount's API credentials?
    automount: true
    # Annotations to add to the service account
    annotations: {}

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

  # Additional volumes on the output Deployment definition.
  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  nodeSelector: {}

  tolerations: []

  affinity: {}

  config:
    entries:
      hosts:
        "http://10.1.1.4:9000/api,http://10.1.1.5:9000/api"

  defaultTLS:
    tls-mode: "no-tls"
    ca-certificate: ""
    client-certificate: ""

  logLevel: "warn"

  containerPort:
    http: 51031

  liveStatus:
    enable: true
    port: 51031
    initialDelaySeconds: 5
    periodSeconds: 2

  readyStatus:
    enable: true
    port: 51031
    initialDelaySeconds: 5
    periodSeconds: 2

rbac:
  ## Configures RBAC.
  create: true
